---
defaults: &defaults
  services:
    - calc-db
    - calc-env
    - calc-redis32
  buildpack: python_buildpack
  stack: cflinuxfs3
  timeout: 180

applications:
- name: calc-dev
  <<: *defaults
  instances: 1
  memory: 1G
  disk_quota: 1024M
  routes:
    - route: calc-dev.app.cloud.gov
  command: bash cf.sh
  router:
    - cipher_suites: RC4-SHA
      min_tls_version: 1.3
  
- name: calc-rqworker
  <<: *defaults
  no-route: true
  health-check-type: none
  instances: 1
  memory: 512M
  command: python manage.py rqworker default

- name: calc-rqscheduler
  <<: *defaults
  no-route: true
  health-check-type: none
  instances: 1
  memory: 256M
  command: python manage.py rqscheduler
  env:
    IS_RQ_SCHEDULER: "yup"
